name: Deploy dist to release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy dist folder to release branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: release   # branche cible
          publish_dir: ./dist       # dossier à publier
          keep_files: false         # supprime l'ancien contenu avant de copier